/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2019-01-08 16:23:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.logInOut;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import java.text.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>登录</title>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"../bootstrap-3.3.7/css/bootstrap.min.css\"/>\r\n");
      out.write("\t\r\n");
      out.write("<script src=\"../bootstrap-3.3.7/js/jquery-2.1.0.js\"  type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../bootstrap-3.3.7/js/bootstrap.min.js\"  type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	SimpleDateFormat ft = 
	new SimpleDateFormat ("yyyy/MM/dd");

      out.write("    \r\n");
      out.write("      \r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write("   input{\r\n");
      out.write("\tmargin-left: 15px;      \t\t\t\t\r\n");
      out.write("     }\r\n");
      out.write("#logReg{\r\n");
      out.write("  width: 330px;\r\n");
      out.write("  height: 300px ; \r\n");
      out.write("  background-color: white ;\r\n");
      out.write("  margin-left: 70% ;\r\n");
      out.write("  margin-top: 12%;\r\n");
      out.write("}\r\n");
      out.write("      \t</style>\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: gray;background-image: url('../img/background.png');overflow:hidden\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"width:100%;height:100%;margin-left:5px\">\t\r\n");
      out.write("\t<span >\r\n");
      out.write("\t\t<img src=\"../img/site_logo.png\" style=\"width:130px;height:40px;margin-top: 5px\"></img>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"margin-left:150px;margin-top:-38px \">\r\n");
      out.write("\t\t<span>\r\n");
      out.write("\t\t\t<font style=\"font-size: 22px;font-family:sans-serif;\">记录生活点滴</font>\r\n");
      out.write("\t\t\t<font id=\"datetime\" style=\"margin-left:10px;color:threedhighlight;font-size: 15px\">");
      out.print( ft.format(new Date()));
      out.write("</font>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<div id=\"logReg\" >\r\n");
      out.write("\t<!-- 选项卡菜单-->\r\n");
      out.write("\t<ul id=\"LogInTab\" class=\"nav nav-tabs\" role=\"tablist\" style=\"float: none;text-align: center\">\r\n");
      out.write("\t    <li class=\"active\" style=\"width: 50%;height: 25px\"><a href=\"#login\" role=\"tab\" data-toggle=\"tab\" >\r\n");
      out.write("\t    <font style=\"font-size: 18px\"><b>登录</b></font></a></li>\r\n");
      out.write("\t    <li style=\"width: 50%\"><a href=\"#regist\" role=\"tab\" data-toggle=\"tab\">\r\n");
      out.write("\t    <font style=\"font-size: 18px;\"><b>注册</b></font></a></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 选项卡面板 -->\r\n");
      out.write("\t<div id=\"logInTabContent\" class=\"tab-content\">\r\n");
      out.write("\t    <div class=\"tab-pane active\" id=\"login\">\r\n");
      out.write("\t\t\t<form role=\"form\" name=\"logform\" action=\"");
      out.print(request.getContextPath() );
      out.write("/logInOut/LogCheck.jsp\" onsubmit=\" return checkdata()\"method=\"post\">\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"logusername\" name=\"logusername\" placeholder=\"请输入用户名\" \r\n");
      out.write("\t\t\t\t    style=\"margin-top: 25px;height:42px;width:300px;\">\r\n");
      out.write("\t\t\t\t    <input type=\"password\" class=\"form-control\" id=\"logpassword\" name=\"logpassword\" placeholder=\"请输入密码\" \r\n");
      out.write("\t\t\t\t    style=\"margin-top: 5px;height: 42px ;width:300px;\">\r\n");
      out.write("\t\t\t\t     <span id=\"error\" style=\"margin-left: 15px;margin-top: 5px\"></span>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\" style=\"width:70%;text-align: center; font-size:18px; margin-left: 55px;margin-top:25px;background-color: orange;color: white\">\r\n");
      out.write("  \t\t\t\t\t登&nbsp;&nbsp;&nbsp;&nbsp;陆</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t    <div class=\"tab-pane \" id=\"regist\">\r\n");
      out.write("\t\t\t\t\t<form role=\"form\"  name=\"regform\" action=\"");
      out.print(request.getContextPath() );
      out.write("/user/RegistOk.jsp\" onsubmit=\"return checksame()\"method=\"post\">\r\n");
      out.write("\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"regusername\" name=\"regusername\"placeholder=\"请输入用户名\" \r\n");
      out.write("\t\t\t\t    style=\"margin-top: 25px;height:42px;width:300px;\">\r\n");
      out.write("\t\t\t\t    <input type=\"password\" class=\"form-control\" id=\"regpassword\" name=\"regpassword\" placeholder=\"请输入密码\" \r\n");
      out.write("\t\t\t\t    style=\"margin-top: 5px;height: 42px ;width:300px;\">\r\n");
      out.write("\t\t\t\t    <input type=\"password\" class=\"form-control\" id=\"regconfirmpwd\" name=\"regconfirmpwd\" placeholder=\"请确认密码\" \r\n");
      out.write("\t\t\t\t    style=\"margin-top: 5px;height: 42px;width:300px; \" >\r\n");
      out.write("\t\t\t\t    <span id=\"hinter\" style=\"margin-left: 15px;margin-top: 5px\"></span>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\"  style=\"width:70%;text-align: center; font-size:18px; margin-left: 55px;background-color: orange;color: white\">\r\n");
      out.write("  \t\t\t\t\t注&nbsp;&nbsp;&nbsp;&nbsp;册</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction checkdata(){\r\n");
      out.write("\t\tif(logform.logusername.value!=''&&logform.logpassword.value!=''){\r\n");
      out.write("\t\t\treturn true ;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(logform.logusername.value==''){\r\n");
      out.write("\t\t\tdocument.getElementById('error').innerHTML=\"<font style='color: red;font-size: 18px' >请输入用户名！ </font>\";\t\r\n");
      out.write("\t\t\tlogform.logusername.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(logform.logpassword.value==''){\r\n");
      out.write("\t\t\tdocument.getElementById('error').innerHTML=\"<font style='color: red;font-size: 18px' >请输入密码！ </font>\";\t\r\n");
      out.write("\t\t\tlogform.logpassword.focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction checksame(){\r\n");
      out.write("\t\tdebugger;\r\n");
      out.write("\t\tif(regform.regpassword.value ==regform.regconfirmpwd.value){\r\n");
      out.write("\t\t\t\tdocument.getElementById('hinter').innerHTML=\"\";\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\tdocument.getElementById('hinter').innerHTML=\"<font style='color: red;font-size: 18px' >两次密码输入不一致，请重新输入! </font>\";\r\n");
      out.write("\t\t\t\tregform.regpassword.value=\"\";\r\n");
      out.write("\t\t\t\tregform.regconfirmpwd.value=\"\";\r\n");
      out.write("\t\t\t\tregform.regpassword.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
